server:
  port: ${PORT:8080}

logging:
  level:
    "org.atmosphere": warn

vaadin:
  launch-browser: true
  allowed-packages: "com.vaadin,org.vaadin,com.flowingcode,de.bbajor.pvs"

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        type: trace
  servlet:
    multipart:
      enabled: false
      max-file-size: 50MB
      max-request-size: 100MB
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:h2:mem:pvs;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  flyway:
    enabled: true
    locations: classpath:db/migration

egk:
  tool-path: "C:/Program Files/OpenSC Project/OpenSC/tools/egk-tool.exe"

domain:
  bundesland: NI
