server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,de.bbajor.pvs

# Let Hibernate update the schema automatically or create it if it does not exist.
#
# DO NOT DO THIS IN PRODUCTION!
#
# Instead, use Flyway or another controlled way of managing your database schema.
# See https://vaadin.com/docs/latest/building-apps/forms-data/add-flyway for instructions.
spring.jpa.hibernate.ddl-auto=create-drop

# SQL ausgeben
spring.jpa.show-sql=true

# Parameter ausgeben
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.type=trace

egk.tool-path=C:/Program Files/OpenSC Project/OpenSC/tools/egk-tool.exe


domain.bundesland=NI

# Wenn du UploadHandler/Receiver benutzt, sonst kann Spring die Request schon abfangen
spring.servlet.multipart.enabled=false

# Optional: Datei-Limits erhöhen (falls Uploads > 1MB fehlschlagen)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

spring.profiles.active=dev