-- Create institution_settings table to prepare for database-per-tenant architecture
-- Each institution gets exactly one settings row with tenant-specific configuration.

CREATE TABLE institution_settings (
    id BIGSERIAL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    institution_id BIGINT NOT NULL UNIQUE,
    display_name VARCHAR(200) NOT NULL,
    legal_name VARCHAR(255),
    description TEXT,
    street VARCHAR(255),
    house_number VARCHAR(50),
    postal_code VARCHAR(20),
    city VARCHAR(255),
    country VARCHAR(255),
    timezone VARCHAR(100) NOT NULL DEFAULT 'Europe/Berlin',
    locale VARCHAR(20) NOT NULL DEFAULT 'de-DE',
    demo_mode BOOLEAN NOT NULL DEFAULT FALSE,
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    contact_fax VARCHAR(50),
    tax_id VARCHAR(100),
    onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE,
    smtp_config_json TEXT,
    notes TEXT,
    remote_llm_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    remote_llm_api_url VARCHAR(500),
    remote_llm_api_key VARCHAR(500),
    remote_llm_monthly_quota INTEGER,
    website_url VARCHAR(500),
    watermark_image BYTEA,
    layout_primary_color VARCHAR(7),
    layout_secondary_color VARCHAR(7),
    layout_background_color VARCHAR(7),
    layout_text_color VARCHAR(7),
    layout_accent_color VARCHAR(7),
    layout_border_radius VARCHAR(10),
    layout_font_family VARCHAR(100),
    kbv_last_import_quarter VARCHAR(20),
    kbv_last_import_version VARCHAR(50),
    kbv_last_imported_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_institution_settings_institution FOREIGN KEY (institution_id) REFERENCES institution(id) ON DELETE CASCADE
);

CREATE INDEX idx_institution_settings_demo_mode ON institution_settings(demo_mode);
CREATE INDEX idx_institution_settings_onboarding ON institution_settings(onboarding_completed);

-- Seed settings for existing institutions using current master data.
INSERT INTO institution_settings (
    institution_id,
    display_name,
    legal_name,
    description,
    street,
    house_number,
    postal_code,
    city,
    country,
    contact_email,
    contact_phone,
    contact_fax,
    tax_id,
    remote_llm_enabled,
    remote_llm_api_url,
    remote_llm_api_key,
    remote_llm_monthly_quota,
    website_url,
    watermark_image,
    layout_primary_color,
    layout_secondary_color,
    layout_background_color,
    layout_text_color,
    layout_accent_color,
    layout_border_radius,
    layout_font_family,
    NULL,
    NULL,
    NULL
)
SELECT id,
       institution_name,
       company_name,
       description,
       street,
       house_number,
       postal_code,
       city,
       country,
       email,
       phone,
       fax,
       tax_id,
       COALESCE(remote_llm_enabled, false),
       remote_llm_api_url,
       remote_llm_api_key,
       remote_llm_monthly_quota,
       website_url,
       watermark_image,
       layout_primary_color,
       layout_secondary_color,
       layout_background_color,
       layout_text_color,
       layout_accent_color,
       layout_border_radius,
       layout_font_family,
       NULL,
       NULL,
       NULL
FROM institution;

-- Ensure updated_at reflects initial creation time.
UPDATE institution_settings SET updated_at = created_at;
